George - dagger implementations
greenfox-academy/bloodstone-tribes-android pull request #16
Opened 2017-06-19 13:29 UTC by georgezsiga

2017-06-19 15:27 UTC, adamgyulavari requested changes

2017-06-19 15:27 UTC, adamgyulavari commented on app/src/main/AndroidManifest.xml
> +        android:name=".MyApp"
@georgezsiga can we name our Application class something different? eg `TribesApplication`

2017-06-19 15:27 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +    private Boolean switchLoginOrMockService = true;
@georgezsiga `private static boolean`

2017-06-19 15:27 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +    private Boolean switchLoginOrMockService = true;
and name accordingly

2017-06-19 15:27 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +                public Call<User> loginWithUser(@Field("username") String username, @Field("password") String password) {
@georgezsiga here should be the building the service with retrofit, instead of some kind of weird implementation

2017-06-19 15:27 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +        if (switchLoginOrMockService == true) {
@georgezsiga think this condition again :)

2017-06-19 15:27 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +    public Boolean getSwitchLoginOrMockService() {
@georgezsiga this method is not needed, just use the variable

2017-06-19 15:27 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/LoginActivity.java
>          preferences = PreferenceManager.getDefaultSharedPreferences(this);
@georgezsiga if you have a provider for sharedpref, you can use it

2017-06-19 15:27 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/LoginActivity.java
>          preferences = PreferenceManager.getDefaultSharedPreferences(this);
or use the `ObjectManager` if you injected it

2017-06-20 07:49 UTC, georgezsiga commented on app/src/main/AndroidManifest.xml
> +        android:name=".MyApp"
done

2017-06-20 07:51 UTC, georgezsiga commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +    private Boolean switchLoginOrMockService = true;
done

2017-06-20 07:51 UTC, georgezsiga commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +    public Boolean getSwitchLoginOrMockService() {
done

2017-06-20 07:53 UTC, georgezsiga commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +        if (switchLoginOrMockService == true) {
done

2017-06-20 08:08 UTC, georgezsiga commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +                public Call<User> loginWithUser(@Field("username") String username, @Field("password") String password) {
done

2017-06-20 10:18 UTC, georgezsiga commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/LoginActivity.java
>          preferences = PreferenceManager.getDefaultSharedPreferences(this);
done

2017-06-20 14:20 UTC, adamgyulavari requested changes

2017-06-20 14:20 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +    private static Boolean isLoginServiceActive = true;
@georgezsiga sorry, it should be `final` too, my mistake. and also naming:
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2017-06-20 14:20 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/LoginActivity.java
>      @Inject LoginService loginService;
@georgezsiga have the `@Inject`-ed fields separated and together

2017-06-20 14:20 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +        this.isLoginServiceActive = switchLoginOrMockService;
@georgezsiga and we dont want to set this either, this will depend only on the environment not on the behaviour of the user or anything

2017-06-20 14:20 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +        return serviceFactory.createMockService(MockLoginService.class, "https://tribes-of-lagopus.herokuapp.com/");
@georgezsiga we dont need parameters here

2017-06-20 14:20 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +        return serviceFactory.createMockService(MockLoginService.class, "https://tribes-of-lagopus.herokuapp.com/");
@georgezsiga remove the parameters from here

2017-06-20 14:27 UTC, georgezsiga commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +    private static Boolean isLoginServiceActive = true;
done

2017-06-20 14:29 UTC, georgezsiga commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +        return serviceFactory.createMockService(MockLoginService.class, "https://tribes-of-lagopus.herokuapp.com/");
done

2017-06-20 14:30 UTC, georgezsiga commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +        this.isLoginServiceActive = switchLoginOrMockService;
done

2017-06-20 14:33 UTC, georgezsiga commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/AppModule.java
> +        return serviceFactory.createMockService(MockLoginService.class, "https://tribes-of-lagopus.herokuapp.com/");
done

2017-06-21 08:37 UTC, adamgyulavari requested changes

2017-06-21 08:37 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/LoginActivity.java
> +        LoginService service = ServiceFactory.createMockService();
@georgezsiga this is why we inject, so we dont need to create this here, at this point there should be an injected `LoginService`

2017-06-21 08:37 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/LoginActivity.java
>          startActivity(intent);
@georgezsiga you should only store the data and start the `MainActivity` if the login was successful

2017-06-21 08:37 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/api/service/ServiceFactory.java
> +        String url = "https://tribes-of-lagopus.herokuapp.com/";
@georgezsiga create a `SERVER_URL` constant instead of this local variable

2017-06-21 08:45 UTC, adamgyulavari approved these changes

2017-06-21 08:45 UTC, merged