Getendpoints
greenfox-academy/bloodstone-tribes-android pull request #19
Opened 2017-06-20 17:50 UTC by rekagiday

apiService for endpoints:
GET /[userId]/kingdom
GET /[userId]/kingdom/buildings
GET /[userId]/kingdom/buildings/[buildingId]

and mock responses in mockApiService

2017-06-21 10:00 UTC, adamgyulavari requested changes

2017-06-21 10:00 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/api/model/gameobject/Kingdom.java
> +public class    Kingdom extends BaseResponse{
@rekagiday unnecessary spaces and space before opening bracket

2017-06-21 10:00 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/api/service/MockApiService.java
> +                callback.onResponse(null, Response.success(new BuildingsResponse(buildings)));
@rekagiday create a building list here with a few buildings

2017-06-21 12:47 UTC, rekagiday commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/api/service/MockApiService.java
> +                callback.onResponse(null, Response.success(new BuildingsResponse(buildings)));
done

2017-06-22 12:45 UTC, adamgyulavari requested changes

2017-06-22 12:45 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/api/service/MockApiService.java
> +    private List<Resource> resources = new ArrayList<>();
@rekagiday dont skip the dummy resources :)

2017-06-22 12:45 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/api/service/MockApiService.java
> +    private List<Troop> troops = new ArrayList<>();
and troops

2017-06-23 10:38 UTC, adamgyulavari approved these changes

2017-06-26 12:13 UTC, merged