George -  settings tests
greenfox-academy/bloodstone-tribes-android pull request #25
Opened 2017-06-23 11:43 UTC by georgezsiga

2017-06-26 10:55 UTC, adamgyulavari requested changes

2017-06-26 10:55 UTC, adamgyulavari commented on app/src/test/java/com/greenfox/tribesoflagopusandroid/SettingsFragmentTest.java
> +        assertEquals("true", settingsFragment.preferences.getString(NOTIFICATION, ""));
@georgezsiga somehow I missed this, but pls use boolean in the preferences

2017-06-26 10:55 UTC, adamgyulavari commented on app/src/test/java/com/greenfox/tribesoflagopusandroid/SettingsFragmentTest.java
> +        SettingsFragment settingsFragment = new SettingsFragment();
@georgezsiga also move the `SettingsFragment` into the `fragments` package

2017-06-26 15:39 UTC, georgezsiga commented
done

2017-06-26 15:44 UTC, adamgyulavari requested changes

2017-06-26 15:44 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/MainActivity.java
> +    public static final Boolean NOTIFICATION = false;
@georgezsiga the preference key should be string, so this was fine like that

2017-06-26 15:44 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/fragments/SettingsFragment.java
> +        notification.setChecked(preferences.getBoolean(String.valueOf(NOTIFICATION), false));
@georgezsiga here the preference value should have been a boolean, so this should look like:
`preferences.getBoolean(NOTIFICATION, false)`

2017-06-26 18:52 UTC, georgezsiga commented
done

2017-06-27 09:28 UTC, adamgyulavari approved these changes

2017-06-27 09:28 UTC, merged