George - simple notification
greenfox-academy/bloodstone-tribes-android pull request #27
Opened 2017-06-26 14:53 UTC by georgezsiga

2017-06-26 15:25 UTC, adamgyulavari requested changes

2017-06-26 15:25 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/LoginActivity.java
> +                        .setSmallIcon(R.drawable.tribes)
@georgezsiga set a large icon as well

2017-06-26 15:50 UTC, georgezsiga commented
done

2017-06-28 09:46 UTC, adamgyulavari approved these changes

2017-06-28 09:46 UTC, merged