George backgroundsync
greenfox-academy/bloodstone-tribes-android pull request #38
Opened 2017-06-29 11:29 UTC by georgezsiga

2017-06-29 12:58 UTC, rekagiday requested changes

2017-06-29 12:58 UTC, rekagiday commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/BasicComponent.java
> +    void inject(AlarmReceiver BroadcastReceiver);
name this according to the styleguide

2017-06-29 12:59 UTC, rekagiday commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/api/model/response/KingdomResponse.java
> +
we don't need this class, we have kingdom model for this

2017-06-29 21:09 UTC, georgezsiga commented
done

2017-06-30 07:16 UTC, rekagiday approved these changes

2017-06-30 07:16 UTC, merged