George refactorrefresh
greenfox-academy/bloodstone-tribes-android pull request #48
Opened 2017-07-04 15:14 UTC by georgezsiga

2017-07-05 10:24 UTC, adamgyulavari requested changes

2017-07-05 10:24 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/MainActivity.java
> +    public Fragment activeFragment = null;
@georgezsiga why not use `BaseFragment` type, then the casting wont be necessery on line 97

2017-07-05 10:24 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/fragments/BuildingsFragment.java
> +    View rootView;
@georgezsiga instead of storing the rootView, store exactly what you use (in this case you only need the adapter)

2017-07-05 12:52 UTC, georgezsiga commented
done

2017-07-14 08:30 UTC, adamgyulavari submitted a review, later dismissed

2017-07-14 08:30 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/tribesoflagopusandroid/fragments/BuildingsFragment.java
> +    public void refreshActiveFragment() {
@georgezsiga this is the method where this fragment gets refreshed, it doesnt know if its the active, the activity knows that. from this perspective its just refreshing

2017-07-14 14:16 UTC, georgezsiga commented
done

2017-07-17 07:21 UTC, viktorhegyi approved these changes
looks good to me

2017-07-17 07:21 UTC, merged